# Generated by Django 3.0.3 on 2020-07-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('Email_Id', models.CharField(max_length=70)),
                ('Username', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('Passport_No', models.IntegerField(default=0, max_length=10)),
                ('Display_Imp', models.ImageField(upload_to='C:\\Users\\Admin\\PycharmProjects\\website\\website')),
            ],
        ),
    ]
